// NOTE: this test is written in Milestone 1 (Task 2) but its CMake target does not
// exist yet — it is built + run once Milestone 3 / Task 7 wires
// VIXEN/libraries/AppFlow/tests/CMakeLists.txt (APPFLOW_GENERATED_HEADER_PATH compile
// def). Do not expect it to build or run until then.
#include <gtest/gtest.h>
#include <fstream>
#include <sstream>
#include <string>

// Reads the committed generated header and asserts key invariants: the provenance
// banner, pinned enum values, and the constexpr tables. A declaration change that
// regenerates the header MUST update this test (that is the guard).
static std::string readFile(const std::string& p) {
    std::ifstream f(p);
    std::stringstream ss; ss << f.rdbuf();
    return ss.str();
}

TEST(AppFlowGolden, HeaderHasProvenanceBanner) {
    const std::string h = readFile(APPFLOW_GENERATED_HEADER_PATH);
    EXPECT_NE(h.find("GENERATED by Yeroket kernel-codegen"), std::string::npos);
    EXPECT_NE(h.find("DO NOT EDIT"), std::string::npos);
}

TEST(AppFlowGolden, EnumValuesArePinned) {
    const std::string h = readFile(APPFLOW_GENERATED_HEADER_PATH);
    EXPECT_NE(h.find("Editing=0"), std::string::npos);
    EXPECT_NE(h.find("Simulating=1"), std::string::npos);
    EXPECT_NE(h.find("Paused=2"), std::string::npos);
    EXPECT_NE(h.find("ToggleLayer=0"), std::string::npos);
}

TEST(AppFlowGolden, ActionDeclTablePresent) {
    const std::string h = readFile(APPFLOW_GENERATED_HEADER_PATH);
    EXPECT_NE(h.find("kActionDecls"), std::string::npos);
    EXPECT_NE(h.find("kTransitions"), std::string::npos);
}

TEST(AppFlowGolden, ParamSignatureEmitted) {
    // The typed param signature (generalized from undertow UiParamSchema) is core, not deferred.
    const std::string h = readFile(APPFLOW_GENERATED_HEADER_PATH);
    EXPECT_NE(h.find("FlowParamType"), std::string::npos);
    EXPECT_NE(h.find("kToggleLayerParams"), std::string::npos);
    EXPECT_NE(h.find("\"layerIndex\""), std::string::npos);
}

// Inc-4 M2: typed key vocabulary + element-trigger/key-default/return-edge tables.
TEST(AppFlowGolden, KeyVocabAndTriggersPresent) {
    const std::string h = readFile(APPFLOW_GENERATED_HEADER_PATH);
    EXPECT_NE(h.find("enum class KeyId"), std::string::npos);
    EXPECT_NE(h.find("enum class KeyMod"), std::string::npos);
    EXPECT_NE(h.find("struct KeyChord"), std::string::npos);
    EXPECT_NE(h.find("enum class FlowScope"), std::string::npos);
    EXPECT_NE(h.find("Undo=1"), std::string::npos);
    EXPECT_NE(h.find("Settings=3"), std::string::npos);
    EXPECT_NE(h.find("kElementTriggers"), std::string::npos);
    EXPECT_NE(h.find("\"layer-{index}-toggle\""), std::string::npos);
    EXPECT_NE(h.find("kKeyDefaults"), std::string::npos);
    EXPECT_NE(h.find("kReturnEdges"), std::string::npos);
    EXPECT_NE(h.find("FlowScope::State"), std::string::npos);   // the Settings override
}

// Inc-4 reframe R2: Return joins the uniform registry as an ordinary action id — a
// back-button reaches it exactly like Esc (design §4.3/D14).
TEST(AppFlowGolden, ReturnActionAndBackButtonTriggerPresent) {
    const std::string h = readFile(APPFLOW_GENERATED_HEADER_PATH);
    EXPECT_NE(h.find("Return=5"), std::string::npos);
    EXPECT_NE(h.find("\"back-button\""), std::string::npos);
}

// Inc-4 reframe R3 (design D16): a Data action names the [View] noun it mutates,
// compile-checked against the [View] schema via --view-schema. Seam M2b made the noun a TYPED
// ViewNounId member (was a raw string); seam M2c retargeted it to EditorNouns_layerMask -- the
// noun LayerControllerViewDataProvider serves -- so the loader wires the Data action end-to-end
// through the day-one direct-field provider.
TEST(AppFlowGolden, DataTargetsTablePresent) {
    const std::string h = readFile(APPFLOW_GENERATED_HEADER_PATH);
    EXPECT_NE(h.find("Data=6"), std::string::npos);
    EXPECT_NE(h.find("kDataTargets"), std::string::npos);
    EXPECT_NE(h.find("ViewNounId::EditorNouns_layerMask"), std::string::npos);
}
