using System.Text;
using Vixen.Codegen.Layout;

namespace Vixen.Codegen.Emit;

public static class CppStructEmitter
{
    static string Cpp(ScalarKind k) => k switch
    {
        ScalarKind.U32 => "uint32_t",
        ScalarKind.I32 => "int32_t",
        ScalarKind.F32 => "float",
        _ => "uint32_t",
    };

    public static string Emit(StructModel m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#pragma once");
        sb.AppendLine("// GENERATED by Vixen.Codegen — DO NOT EDIT. Regenerate from the canonical [GpuStruct].");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine("#include <cstddef>");
        sb.AppendLine("namespace Vixen::Gpu {");
        sb.AppendLine($"struct {m.Name} {{");
        foreach (var f in m.Fields) sb.AppendLine($"    {Cpp(f.Kind)} {f.Name};");
        sb.AppendLine("};");
        sb.AppendLine($"static_assert(sizeof({m.Name}) == {m.SizeBytes}, \"{m.Name} std430 size\");");
        foreach (var f in m.Fields)
            sb.AppendLine($"static_assert(offsetof({m.Name}, {f.Name}) == {f.Offset}, \"{f.Name}@{f.Offset}\");");
        sb.AppendLine("} // namespace Vixen::Gpu");
        return sb.ToString();
    }
}
