using System.Text;
using Vixen.Codegen.Layout;

namespace Vixen.Codegen.Emit;

public static class GlslStructEmitter
{
    static string Glsl(ScalarKind k) => k switch
    {
        ScalarKind.U32 => "uint",
        ScalarKind.I32 => "int",
        ScalarKind.F32 => "float",
        _ => throw new System.NotSupportedException($"unmapped ScalarKind {k}"),
    };

    public static string Emit(StructModel m)
    {
        string guard = m.Name.ToUpperInvariant() + "_GLSL";
        var sb = new StringBuilder();
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine("// GENERATED by Vixen.Codegen — DO NOT EDIT.");
        sb.AppendLine($"struct {m.Name} {{");
        foreach (var f in m.Fields) sb.AppendLine($"    {Glsl(f.Kind)} {f.Name};");
        sb.AppendLine("};");
        sb.AppendLine($"#endif // {guard}");
        // Normalize to LF so emitted bytes are host-independent.
        return sb.ToString().Replace("\r\n", "\n");
    }
}
