include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/VixenWriteIfDifferent.cmake")

# The default cache is outside source checkouts. Tests/isolated lanes can override
# it with an untracked directory inside their own worktree.
if(NOT DEFINED VIXEN_KERNEL_CACHE_DIR)
    if(DEFINED ENV{XDG_CACHE_HOME} AND NOT "$ENV{XDG_CACHE_HOME}" STREQUAL "")
        set(_vixen_kernel_cache "$ENV{XDG_CACHE_HOME}/vixen/kernel-codegen")
    elseif(WIN32 AND NOT "$ENV{LOCALAPPDATA}" STREQUAL "")
        set(_vixen_kernel_cache "$ENV{LOCALAPPDATA}/VIXEN/kernel-codegen")
    elseif(NOT "$ENV{HOME}" STREQUAL "")
        set(_vixen_kernel_cache "$ENV{HOME}/.cache/vixen/kernel-codegen")
    else()
        message(FATAL_ERROR "[codegen] set VIXEN_KERNEL_CACHE_DIR: no user cache location was found")
    endif()
    set(VIXEN_KERNEL_CACHE_DIR "${_vixen_kernel_cache}" CACHE PATH
        "Content-addressed pinned kernel snapshots and built CodegenTool cache")
endif()

function(vixen_kernel_snapshot repository sha out_directory)
    string(LENGTH "${sha}" _length)
    if(NOT _length EQUAL 40 OR NOT sha MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "[codegen] YEROKET_KERNEL_SHA must be a full commit SHA: ${sha}")
    endif()
    set(_directory "${VIXEN_KERNEL_CACHE_DIR}/sources/yeroket-${sha}")
    file(MAKE_DIRECTORY "${VIXEN_KERNEL_CACHE_DIR}/sources")
    file(LOCK "${_directory}.lock" GUARD FUNCTION TIMEOUT 300 RESULT_VARIABLE _lock)
    if(NOT _lock STREQUAL "0")
        message(FATAL_ERROR "[codegen] cannot lock kernel snapshot ${sha}: ${_lock}")
    endif()
    set(_stamp "${_directory}/.archive-complete")
    if(EXISTS "${_stamp}")
        file(READ "${_stamp}" _recorded_sha)
        if(_recorded_sha STREQUAL "${sha}\n")
            set(${out_directory} "${_directory}" PARENT_SCOPE)
            message(STATUS "[codegen] reusing pinned kernel snapshot: ${_directory}")
            return()
        endif()
        message(FATAL_ERROR "[codegen] invalid snapshot stamp: ${_stamp}")
    endif()

    find_program(_vixen_kernel_git NAMES git REQUIRED)
    execute_process(COMMAND "${_vixen_kernel_git}" -C "${repository}" cat-file -e "${sha}^{commit}"
        RESULT_VARIABLE _exists ERROR_VARIABLE _error OUTPUT_QUIET)
    if(NOT _exists EQUAL 0)
        message(FATAL_ERROR "[codegen] pinned kernel ${sha} unavailable from ${repository}: ${_error}")
    endif()
    # All readers of this cache entry hold the same lock. A failed extraction never
    # publishes a complete directory; a later configure can remove its staging data.
    set(_stage "${_directory}.partial")
    set(_archive "${_directory}.tar")
    file(REMOVE_RECURSE "${_stage}")
    file(MAKE_DIRECTORY "${_stage}")
    execute_process(COMMAND "${_vixen_kernel_git}" -C "${repository}" archive
        --format=tar --output "${_archive}" "${sha}"
        RESULT_VARIABLE _archived ERROR_VARIABLE _error)
    if(NOT _archived EQUAL 0)
        message(FATAL_ERROR "[codegen] cannot archive pinned kernel ${sha}: ${_error}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${_archive}"
        WORKING_DIRECTORY "${_stage}" RESULT_VARIABLE _extracted ERROR_VARIABLE _error)
    if(NOT _extracted EQUAL 0)
        message(FATAL_ERROR "[codegen] cannot extract pinned kernel ${sha}: ${_error}")
    endif()
    file(WRITE "${_stage}/.archive-complete" "${sha}\n")
    if(EXISTS "${_directory}")
        message(FATAL_ERROR "[codegen] incomplete unmanaged snapshot at ${_directory}; remove it before retrying")
    endif()
    file(RENAME "${_stage}" "${_directory}")
    file(REMOVE "${_archive}")
    set(${out_directory} "${_directory}" PARENT_SCOPE)
    message(STATUS "[codegen] cached pinned kernel snapshot: ${_directory}")
endfunction()

# CMake config scripts use bracket arguments so spaces/backslashes in paths and
# semicolons separating command arguments retain their meaning.
function(vixen_codegen_build_config output cache_dir cached_binary_dir local_binary_dir stamp)
    set(_content "set(VIXEN_CODEGEN_CACHE_DIR [==[${cache_dir}]==])\n")
    string(APPEND _content "set(VIXEN_CODEGEN_CACHED_BIN [==[${cached_binary_dir}]==])\n")
    string(APPEND _content "set(VIXEN_CODEGEN_LOCAL_BIN [==[${local_binary_dir}]==])\n")
    string(APPEND _content "set(VIXEN_CODEGEN_LOCAL_STAMP [==[${stamp}]==])\n")
    string(APPEND _content "set(VIXEN_CODEGEN_BUILD_COMMAND\n")
    foreach(_argument IN LISTS ARGN)
        string(APPEND _content "    [==[${_argument}]==]\n")
    endforeach()
    string(APPEND _content ")\n")
    vixen_write_if_different("${output}" "${_content}")
endfunction()
