# VixenNodeManifest.cmake
#
# Configure-time extraction of "which RenderGraph node TYPES does this app's graph-builder
# code actually instantiate" — the manifest that drives scoped node linkage
# (Graph-Derived-Node-Linkage-Spec-2026-07 §2.2). Parses `AddNode<XNodeType>(` call sites out
# of a fixed list of Build*.cpp source files (NOT #include lines — an include can in principle
# be unused; the call site is the actual usage) and writes the unique, sorted set of node type
# names into a generated .cmake file as a single list variable, for a later `include()`.
#
# This is a plain regex scan (file(STRINGS ... REGEX ...)), not a C++ parser — sufficient
# because every call site in this codebase is a single-line `AddNode<TypeName>(` token
# sequence (confirmed by inspection of all 5 Build*.cpp files at Inc-1 M3 time: no multi-line
# template args, no indirection through a helper/macro, no use of the legacy
# `AddNode("TypeName", ...)` runtime-string overload). If a future call site doesn't match this
# shape, it silently won't appear in the manifest — see spec §3 for the resulting (loud, at
# graph-build time) failure mode.
#
# Usage:
#   vixen_generate_node_manifest(<out-file> <SOURCES> src1.cpp [src2.cpp ...])
#
#   <out-file>  Absolute path to the generated .cmake file to write. On success it defines
#               VIXEN_APP_USED_NODE_TYPES as a `set(VIXEN_APP_USED_NODE_TYPES A B C ...)` list.
#   SOURCES     Absolute paths to the Build*.cpp files to scan.
#
# Runs at CMake CONFIGURE time so the generated file is ready before any target needs it.

function(vixen_generate_node_manifest out_file)
    cmake_parse_arguments(VGNM "" "" "SOURCES" ${ARGN})

    set(_node_types "")
    foreach(src_file IN LISTS VGNM_SOURCES)
        if(NOT EXISTS "${src_file}")
            message(FATAL_ERROR "vixen_generate_node_manifest: source file does not exist: ${src_file}")
        endif()

        file(STRINGS "${src_file}" _matched_lines REGEX "AddNode<[A-Za-z_][A-Za-z0-9_]*>")
        foreach(_line IN LISTS _matched_lines)
            string(REGEX MATCHALL "AddNode<[A-Za-z_][A-Za-z0-9_]*>" _calls "${_line}")
            foreach(_call IN LISTS _calls)
                string(REGEX REPLACE "AddNode<([A-Za-z_][A-Za-z0-9_]*)>" "\\1" _type_name "${_call}")
                list(APPEND _node_types "${_type_name}")
            endforeach()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _node_types)
    list(SORT _node_types)

    get_filename_component(_out_dir "${out_file}" DIRECTORY)
    file(MAKE_DIRECTORY "${_out_dir}")

    set(_content "# Auto-generated by cmake/VixenNodeManifest.cmake at configure time. Do not edit.\n")
    string(APPEND _content "# Source: AddNode<T>(...) call sites in:\n")
    foreach(src_file IN LISTS VGNM_SOURCES)
        string(APPEND _content "#   ${src_file}\n")
    endforeach()
    string(APPEND _content "set(VIXEN_APP_USED_NODE_TYPES\n")
    foreach(_type_name IN LISTS _node_types)
        string(APPEND _content "    ${_type_name}\n")
    endforeach()
    string(APPEND _content ")\n")

    file(WRITE "${out_file}" "${_content}")

    list(LENGTH _node_types _node_count)
    message(STATUS "vixen_generate_node_manifest: wrote ${_node_count} node type(s) to ${out_file}")
endfunction()
