include_guard(GLOBAL)

function(vixen_configure_compiler_paths)
    # This engine uses headers, not named C++ modules. CMP0155 otherwise enables
    # scanning on recent GCC/MSVC, adding module maps and uncacheable flags to
    # ordinary C++23 TUs. An explicit caller setting or CXX_MODULES file set wins.
    if(NOT DEFINED CMAKE_CXX_SCAN_FOR_MODULES)
        set(CMAKE_CXX_SCAN_FOR_MODULES OFF PARENT_SCOPE)
    endif()
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        return()
    endif()
    set(_roots "${VIXEN_ROOT}" "${CMAKE_BINARY_DIR}" "${FETCHCONTENT_BASE_DIR}")
    set(_mapped "/vixen" "/vixen-build" "/vixen-deps")
    if(VULKAN_PATH)
        list(APPEND _roots "${VULKAN_PATH}")
        list(APPEND _mapped "/vixen-vulkan")
    endif()
    list(LENGTH _roots _count)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
        list(GET _roots ${_index} _root)
        list(GET _mapped ${_index} _destination)
        if(_root)
            foreach(_kind file debug macro)
                add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:-f${_kind}-prefix-map=${_root}=${_destination}>")
            endforeach()
        endif()
    endforeach()
endfunction()

# Call after subdirectories have declared their targets. Stable angle includes
# keep CMake's generated cmake_pch.hxx content identical between worktrees.
function(vixen_cache_compatible_pch directory)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        return()
    endif()
    get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(_target IN LISTS _targets)
        get_target_property(_headers ${_target} PRECOMPILE_HEADERS)
        if(NOT _headers)
            continue()
        endif()
        set(_stable_headers)
        foreach(_header IN LISTS _headers)
            set(_stable "${_header}")
            foreach(_root IN ITEMS "${VIXEN_ROOT}" "${FETCHCONTENT_BASE_DIR}" "${CMAKE_BINARY_DIR}")
                if(NOT _root)
                    continue()
                endif()
                string(FIND "${_header}" "${_root}/" _prefix)
                if(_prefix EQUAL 0)
                    string(LENGTH "${_root}/" _offset)
                    string(SUBSTRING "${_header}" ${_offset} -1 _relative)
                    set(_stable "<${_relative}>")
                    target_include_directories(${_target} PRIVATE "${_root}")
                    break()
                endif()
            endforeach()
            list(APPEND _stable_headers "${_stable}")
        endforeach()
        set_property(TARGET ${_target} PROPERTY PRECOMPILE_HEADERS "${_stable_headers}")
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            target_compile_options(${_target} PRIVATE -fno-pch-timestamp)
        endif()
        get_target_property(_launcher ${_target} CXX_COMPILER_LAUNCHER)
        set(_ccache FALSE)
        foreach(_part IN LISTS _launcher)
            get_filename_component(_program "${_part}" NAME)
            if(NOT _part MATCHES "=" AND _program MATCHES "^ccache(\\.exe)?$")
                set(_ccache TRUE)
            endif()
        endforeach()
        if(_ccache)
            set(_sloppiness "pch_defines,time_macros")
            if(NOT "$ENV{CCACHE_SLOPPINESS}" STREQUAL "")
                string(APPEND _sloppiness ",$ENV{CCACHE_SLOPPINESS}")
            endif()
            set_property(TARGET ${_target} PROPERTY CXX_COMPILER_LAUNCHER
                "${CMAKE_COMMAND};-E;env;CCACHE_SLOPPINESS=${_sloppiness};${_launcher}")
        endif()
    endforeach()
    get_property(_subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(_subdirectory IN LISTS _subdirectories)
        vixen_cache_compatible_pch("${_subdirectory}")
    endforeach()
endfunction()
