#pragma once
#include "Recipe/RecipeRegistry.h"
#include "Recipe/SdfRecipeCodegenGlsl.h"
#include <cstdint>
#include <sstream>
#include <string>

namespace Vixen::SVO::Recipe {

// EmitSpecializedRecipeComputeShader — Recipe GPU Instance Bucketing Inc2 M2 (Task 5).
//
// GLSL sibling of SdfRecipeCodegen.h's EmitProceduralComputeShader (the existing HLSL
// "specialized single-recipe trace shader" precedent) — same idea (field function + a fixed
// trace main(), concatenated into ONE standalone compute shader with zero switch-dispatch
// overhead for any recipeId other than the one it was compiled for), but GLSL, and driven by
// this milestone's bucketed-dispatch data instead of a full-screen sweep:
//
//   - reuses EmitProceduralFieldFunctionGlsl for JUST this one recipe's bytecode (NOT
//     SpliceProceduralRecipesIntoSource's multi-recipe switch — this is deliberately the
//     smaller, simpler compile Task 5 calls for).
//   - main() is dispatched via vkCmdDispatchIndirect (Task 4) sized to THIS recipe's bucket's
//     screen-space coverage rect (RecipeInstanceBucketing.comp's mode==2 output) — one thread
//     per pixel WITHIN that rect (not the full screen), offset by the rect's own minX/minY
//     (bound via a small push-constant, see below).
//   - loops ONLY this bucket's compacted member instance list (RecipeInstanceBucketing.comp's
//     bucketIndices[] slice for this recipeId) — never touches bodyInstances[] entries outside
//     this bucket, unlike the tier-0 switch's full-instance loop.
//   - per design doc §3.3 (resolved): writes HitRecord via a PLAIN (non-atomic)
//     read-compare-conditionally-overwrite (`if (hitT < hitRecords[idx].hitT) ...`), correct
//     because MultiDispatchNode's default autoBarriers_ serializes this dispatch against every
//     other bucket's dispatch touching the same HitRecord SSBO (write-after-write hazard,
//     FrameSyncScheduler::NeedsSync) — no atomics needed, see the design doc for the full proof.
//
// Self-contained binding namespace starting at 0 (mirrors RecipeInstanceBucketing.comp's own
// "does not depend on the uber-shader splice chain" precedent) — this shader does NOT #include
// SceneBindings.glsl (that pulls in the ENTIRE tier-0 traversal machinery, including the very
// switch this specialized shader exists to avoid). It needs only: this bucket's compacted
// instance-index list + bodyInstances[] (for worldPos/recipeParams), the camera basis (own
// push-constant block, same fields as SceneBindings.glsl's PushConstants for the ray-gen math),
// and the shared HitRecord SSBO (binding 18, the SAME binding the tier-0 path writes, so both
// paths composite into ONE shared per-pixel record).
//
// `sdfCoreKernelsGlsl` is the VERBATIM content of libraries/SVO/shaders/recipe/SdfCoreKernels.glsl
// (the SdfCore_* kernel set the emitted field function calls), passed in and textually inlined
// rather than #include-d — mirrors EmitProceduralComputeShader's (SdfRecipeCodegen.h) own
// sdfCoreHlsl-as-parameter convention exactly. This is required, not stylistic:
// ShaderManagement::ShaderCompiler::Compile takes ALREADY-PREPROCESSED source with no #include
// resolution (no includer/-I support), unlike the build-time glslc CLI compiles other shaders in
// this codebase use — the caller must therefore inline this shader's own dependency itself before
// calling Compile, exactly as EmitProceduralComputeShader's caller already does for the HLSL core.
inline std::string EmitSpecializedRecipeComputeShader(
    const RecipeRegistry::RecipeEntry& entry,
    uint32_t recipeId,
    const std::string& sdfCoreKernelsGlsl)
{
    std::string fieldFn = EmitProceduralFieldFunctionGlsl(
        entry.bytecode.data(), static_cast<uint32_t>(entry.bytecode.size()), recipeId);

    std::ostringstream out;
    out << "#version 460\n\n";
    out << "// Recipe GPU Instance Bucketing Inc2 M2 Task 5 -- specialized single-recipe shader\n";
    out << "// for recipeId " << recipeId << ". Machine-generated by\n";
    out << "// EmitSpecializedRecipeComputeShader -- do not hand-edit.\n\n";
    out << "layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;\n\n";

    out << sdfCoreKernelsGlsl << "\n\n";
    out << fieldFn << "\n";

    // Standalone binding namespace (0..4), mirrors RecipeInstanceBucketing.comp's own
    // self-contained-shader precedent. bodyInstances[] is byte-identical to the shared
    // BodyInstanceGpu layout (binding 10 in SceneBindings.glsl) but declared fresh here at
    // binding 0, since this shader has no other reason to #include the shared chain.
    out << R"(
struct BodyInstance {
    vec3  worldPos;          // 0
    float renderScale;       // 12
    vec3  color;             // 16
    uint  octreeIndex;       // 28
    uint  providerKind;      // 32
    uint  recipeId;          // 36
    float recipeParams[6];   // 40..63
};
layout(std430, binding = 0) readonly buffer BodyInstanceBuffer { BodyInstance bodyInstances[]; };

// This recipe's compacted member instance-index list (RecipeInstanceBucketing.comp's
// bucketIndices[] slice for THIS recipeId, uploaded/aliased at binding 1 — one flat array of
// instance indices, memberCount entries valid).
layout(std430, binding = 1) readonly buffer BucketMembersBuffer { uint bucketMembers[]; };

#ifndef HITRECORD_GLSL
#define HITRECORD_GLSL
#define HITRECORD_FLAG_HIT 0x1u
struct HitRecord {
    vec3  albedo;
    float roughness;
    vec3  worldNormal;
    float hitT;
    vec3  worldPos;
    uint  flags;
    uint  _pad0[3];
};
#endif
layout(std430, binding = 2) buffer HitRecordBuffer { HitRecord hitRecords[]; };

layout(push_constant) uniform Push {
    vec3  cameraPos;
    float _p0;
    vec3  cameraDir;
    float fov;
    vec3  cameraUp;
    float aspect;
    vec3  cameraRight;
    float _p1;
    uint  memberCount;   // valid entries in bucketMembers[]
    uint  screenWidth;   // FULL screen width (for HitRecord's row-major index, NOT the rect width)
    uint  screenHeight;  // FULL screen height
    uint  rectMinX;      // this bucket's coverage rect origin (indirect dispatch is offset by this)
    uint  rectMinY;
    float boundRadius;   // this recipe's bound-sphere radius (world-space, sphere-march bound)
    float stepRelaxation;// this recipe's registered step relaxation (0.0 < r <= 1.0)
} pc;

vec3 getRayDir(vec2 uv) {
    float tanHalfFov = tan(radians(pc.fov * 0.5));
    vec2 ndc = uv * 2.0 - 1.0;
    ndc.y = -ndc.y;
    return normalize(pc.cameraDir + pc.cameraRight * ndc.x * tanHalfFov * pc.aspect
                                   + pc.cameraUp    * ndc.y * tanHalfFov);
}

)";
    out << "void main() {\n";
    out << "    ivec2 rectCoord = ivec2(gl_GlobalInvocationID.xy);\n";
    out << "    ivec2 pixelCoords = rectCoord + ivec2(int(pc.rectMinX), int(pc.rectMinY));\n";
    out << "    if (pixelCoords.x >= int(pc.screenWidth) || pixelCoords.y >= int(pc.screenHeight)) return;\n";
    out << "    if (pixelCoords.x < 0 || pixelCoords.y < 0) return;\n\n";
    out << "    vec2 uv = (vec2(pixelCoords) + 0.5) / vec2(float(pc.screenWidth), float(pc.screenHeight));\n";
    out << "    vec3 rayOrigin = pc.cameraPos;\n";
    out << "    vec3 rayDir    = getRayDir(uv);\n\n";
    out << "    bool  anyHit = false;\n";
    out << "    float bestT  = 1e30;\n";
    out << "    vec3  bestNormal = vec3(0.0, 1.0, 0.0);\n";
    out << "    vec3  bestColor  = vec3(1.0);\n\n";
    out << "    for (uint m = 0u; m < pc.memberCount; ++m) {\n";
    out << "        uint instIdx = bucketMembers[m];\n";
    out << "        BodyInstance inst = bodyInstances[instIdx];\n";
    out << "        // Bound-sphere center is recipe-LOCAL, translated by this instance's worldPos\n";
    out << "        // (mirrors RecipeInstanceBucketing.comp's same convention, and TraceWorld.glsl's\n";
    out << "        // own boundCenter-from-getRecipeBoundSphere+worldPos combination). The field\n";
    out << "        // function itself (sdfRecipe_<id>) evaluates in WORLD space directly -- mirrors\n";
    out << "        // traceUberRecipeBody's evalRecipeField(recipeId, p, params) call, which passes\n";
    out << "        // the raw world-space march point with NO per-instance offset subtraction.\n";
    out << "        vec3 boundCenter = inst.worldPos;\n\n";
    out << "        vec3  oc = rayOrigin - boundCenter;\n";
    out << "        float b  = dot(oc, rayDir);\n";
    out << "        float c  = dot(oc, oc) - pc.boundRadius * pc.boundRadius;\n";
    out << "        float disc = b * b - c;\n";
    out << "        if (disc < 0.0) continue;\n";
    out << "        float sq = sqrt(disc);\n";
    out << "        float tNear = max(-b - sq, 0.0);\n";
    out << "        float tFar  = -b + sq;\n";
    out << "        if (tFar < 0.0 || tNear >= bestT) continue;\n\n";
    out << "        float t = tNear;\n";
    out << "        const int   MAX_STEPS = 128;\n";
    out << "        const float EPS = 1e-3;\n";
    out << "        for (int i = 0; i < MAX_STEPS; ++i) {\n";
    out << "            vec3  p = rayOrigin + rayDir * t;\n";
    out << "            float d = sdfRecipe_" << recipeId << "(p, inst.recipeParams);\n";
    out << "            if (d < EPS) {\n";
    out << "                if (t < bestT) {\n";
    out << "                    const float h = 1e-3;\n";
    out << "                    vec2 e = vec2(h, 0.0);\n";
    out << "                    float gx = sdfRecipe_" << recipeId << "(p + e.xyy, inst.recipeParams) - sdfRecipe_" << recipeId << "(p - e.xyy, inst.recipeParams);\n";
    out << "                    float gy = sdfRecipe_" << recipeId << "(p + e.yxy, inst.recipeParams) - sdfRecipe_" << recipeId << "(p - e.yxy, inst.recipeParams);\n";
    out << "                    float gz = sdfRecipe_" << recipeId << "(p + e.yyx, inst.recipeParams) - sdfRecipe_" << recipeId << "(p - e.yyx, inst.recipeParams);\n";
    out << "                    bestT = t;\n";
    out << "                    bestNormal = normalize(vec3(gx, gy, gz));\n";
    out << "                    bestColor  = inst.color;\n";
    out << "                    anyHit = true;\n";
    out << "                }\n";
    out << "                break;\n";
    out << "            }\n";
    out << "            t += d * pc.stepRelaxation;\n";
    out << "            if (t > tFar) break;\n";
    out << "        }\n";
    out << "    }\n\n";
    out << "    if (!anyHit) return;\n\n";
    out << "    uint hitIdx = uint(pixelCoords.y) * pc.screenWidth + uint(pixelCoords.x);\n";
    out << "    // Design doc Sec3.3: plain (non-atomic) read-compare-conditionally-overwrite.\n";
    out << "    // Correct because MultiDispatchNode's default autoBarriers_ serializes this\n";
    out << "    // dispatch against every other pass touching HitRecord (write-after-write\n";
    out << "    // hazard), so no two buckets' dispatches can race on the same pixel.\n";
    out << "    if (bestT < hitRecords[hitIdx].hitT || hitRecords[hitIdx].flags == 0u) {\n";
    out << "        HitRecord rec;\n";
    out << "        rec.albedo = bestColor;\n";
    out << "        rec.roughness = 1.0;\n";
    out << "        rec.worldNormal = bestNormal;\n";
    out << "        rec.hitT = bestT;\n";
    out << "        rec.worldPos = rayOrigin + rayDir * bestT;\n";
    out << "        rec.flags = HITRECORD_FLAG_HIT;\n";
    out << "        rec._pad0 = uint[3](0u, 0u, 0u);\n";
    out << "        hitRecords[hitIdx] = rec;\n";
    out << "    }\n";
    out << "}\n";

    return out.str();
}

} // namespace Vixen::SVO::Recipe
