#include <gtest/gtest.h>
#include "Core/NodeTypeRegistry.h"
#include "Core/NodeRegistration.h"
// Type-keyed spot-checks (robust — no fragile name strings):
#include "Nodes/CameraNode.h"
#include "Nodes/DeviceNode.h"
#include "Nodes/VoxelGridNode.h"
#include "Nodes/PresentNode.h"
#include "Nodes/BufferSyncGathererNode.h"  // Sampled Lighting Inc3 M5: variadic VkBuffer sync gatherer

using namespace Vixen::RenderGraph;

// Exact expected count, generated by tests/CMakeLists.txt from RENDERGRAPH_NODE_SOURCES'
// length (libraries/RenderGraph/CMakeLists.txt) -- single source of truth, so this can't drift
// out of sync with the real node list the way a second hand-maintained magic number could.
#ifndef RENDERGRAPH_EXPECTED_NODE_TYPE_COUNT
#error "RENDERGRAPH_EXPECTED_NODE_TYPE_COUNT not defined -- tests/CMakeLists.txt must set it via target_compile_definitions"
#endif

// If RenderGraphNodes is NOT whole-archived, the per-node static registrars are
// stripped by the linker and the registry comes back nearly empty — this test is
// the guard that catches that (and confirms RegisterAllNodes works at all).
TEST(NodeSelfRegistration, RegistersAllBuiltInNodes) {
    NodeTypeRegistry registry;
    RegisterAllNodes(registry);

    // Exact count (not >=): a node silently vanishing from the registry must fail this test,
    // not just adding one. The stripping bug drives this to ~0, so any deviation is a real bug.
    EXPECT_EQ(registry.GetNodeTypeCount(), static_cast<size_t>(RENDERGRAPH_EXPECTED_NODE_TYPE_COUNT));

    // Stable, type-keyed lookups across node groups:
    EXPECT_TRUE(registry.Has<CameraNodeType>());
    EXPECT_TRUE(registry.Has<DeviceNodeType>());
    EXPECT_TRUE(registry.Has<VoxelGridNodeType>());
    EXPECT_TRUE(registry.Has<PresentNodeType>());
    EXPECT_TRUE(registry.Has<BufferSyncGathererNodeType>());
}

// RegisterAllNodes replays into whatever registry instance it is given — proves
// the manifest is per-EngineContext-friendly (two independent registries).
TEST(NodeSelfRegistration, ReplaysIntoEachRegistryInstance) {
    NodeTypeRegistry a;
    NodeTypeRegistry b;
    RegisterAllNodes(a);
    RegisterAllNodes(b);
    EXPECT_EQ(a.GetNodeTypeCount(), b.GetNodeTypeCount());
    EXPECT_EQ(a.GetNodeTypeCount(), static_cast<size_t>(RENDERGRAPH_EXPECTED_NODE_TYPE_COUNT));
}
