if(NOT VIXEN_FAIL_SCENARIOS)
    message(STATUS "⊗ fail-scenario tests skipped (VIXEN_FAIL_SCENARIOS=OFF)")
    return()
endif()
if(TARGET GTest::gtest_main)
    add_executable(test_fail_scenario_registry FailScenarios/test_fail_scenario_registry.cpp)
    target_include_directories(test_fail_scenario_registry PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../include)
    target_link_libraries(test_fail_scenario_registry PRIVATE GTest::gtest_main RenderGraph)
    set_target_properties(test_fail_scenario_registry PROPERTIES FOLDER "Tests/RenderGraph Tests")
    gtest_discover_tests(test_fail_scenario_registry)
    message(STATUS "✓ test_fail_scenario_registry configured")
endif()
