#pragma once

/**
 * @file compute_shader_naming.h
 * @brief AUTO-GENERATED BY SDI - Shader resource definitions from reflection
 *
 * This file is generated by the Shader Definition Interface (SDI) tool from
 * shader reflection data. It contains resource requirement structs with embedded
 * metadata for the resource gatherer system.
 *
 * IMPORTANT: This is an example of what SDI should generate. The actual SDI
 * generator should produce files in this exact format.
 */

#include <vulkan/vulkan.h>
#include <vector>

namespace Vixen::RenderGraph::ShaderBundles {

// ============================================================================
// COMPUTE SHADER RESOURCES
// Generated from: shaders/compute/image_process.comp.spv
// ============================================================================

/**
 * @brief Resource requirements for compute shader
 *
 * This struct is generated from shader reflection and defines all resources
 * needed by the compute shader. The _Reflection metadata enables automatic
 * resource gathering.
 *
 * Descriptor Sets:
 *   Set 0: Uniform buffers
 *   Set 1: Input images (sampled)
 *   Set 2: Output images (storage)
 *
 * Pipeline: Compute pipeline and layout
 */
struct ComputeShaderResources {
    // Descriptor Set 0: Uniforms
    std::vector<VkBuffer> uniformBuffers;

    // Descriptor Set 1: Input textures
    std::vector<VkImageView> inputImages;

    // Descriptor Set 2: Output textures
    std::vector<VkImageView> outputImages;

    // Pipeline state
    VkPipeline computePipeline;
    VkPipelineLayout pipelineLayout;

    // ========================================================================
    // METADATA FOR RESOURCE GATHERER (auto-generated by SDI)
    // ========================================================================
    struct _Reflection {
        using FieldTypes = std::tuple<
            std::vector<VkBuffer>,      // uniformBuffers
            std::vector<VkImageView>,   // inputImages
            std::vector<VkImageView>,   // outputImages
            VkPipeline,                 // computePipeline
            VkPipelineLayout            // pipelineLayout
        >;
        static constexpr size_t FieldCount = 5;
    };
};

// ============================================================================
// IMAGE PROCESSING SHADER
// Generated from: shaders/post_process/blur.comp.spv
// ============================================================================

/**
 * @brief Resources for image processing shader
 */
struct ImageProcessingShader {
    VkImageView inputImage;
    VkImageView outputImage;
    VkBuffer parametersBuffer;
    VkPipeline pipeline;

    // Metadata (auto-generated by SDI)
    struct _Reflection {
        using FieldTypes = std::tuple<
            VkImageView,    // inputImage
            VkImageView,    // outputImage
            VkBuffer,       // parametersBuffer
            VkPipeline      // pipeline
        >;
        static constexpr size_t FieldCount = 4;
    };
};

// ============================================================================
// PARTICLE SIMULATION SHADER
// Generated from: shaders/particles/simulate.comp.spv
// ============================================================================

/**
 * @brief Resources for particle simulation compute shader
 */
struct ParticleSimulationShader {
    VkBuffer positionBuffer;
    VkBuffer velocityBuffer;
    VkImageView forceFieldTexture;
    VkBuffer uniformBuffer;
    VkPipeline computePipeline;

    // Metadata (auto-generated by SDI)
    struct _Reflection {
        using FieldTypes = std::tuple<
            VkBuffer,       // positionBuffer
            VkBuffer,       // velocityBuffer
            VkImageView,    // forceFieldTexture
            VkBuffer,       // uniformBuffer
            VkPipeline      // computePipeline
        >;
        static constexpr size_t FieldCount = 5;
    };
};

} // namespace Vixen::RenderGraph::ShaderBundles

// ============================================================================
// USAGE EXAMPLE
// ============================================================================

/*

// STEP 1: Include the naming.h file (the ONLY config needed)
#include "ShaderBundles/compute_shader_naming.h"
#include "Nodes/ShaderBundleGatherer.h"

using namespace Vixen::RenderGraph;
using namespace Vixen::RenderGraph::ShaderBundles;

// STEP 2: Create gatherer - NO manual configuration!
ShaderBundleGatherer<ComputeShaderResources> gatherer;

// The gatherer automatically knows:
// - How many inputs (5)
// - Type of each input (from _Reflection::FieldTypes)
// - Field order (matches struct definition)

// STEP 3: Connect inputs (order matches naming.h)
gatherer.input<0>().connectFrom(uniformBuffersSlot);  // vector<VkBuffer>
gatherer.input<1>().connectFrom(inputImagesSlot);     // vector<VkImageView>
gatherer.input<2>().connectFrom(outputImagesSlot);    // vector<VkImageView>
gatherer.input<3>().connectFrom(pipelineSlot);        // VkPipeline
gatherer.input<4>().connectFrom(layoutSlot);          // VkPipelineLayout

// Wrong type? Compile error!
// gatherer.input<0>().connectFrom(imageSlot);  // ERROR: wrong type

// STEP 4: Execute and get typed output
gatherer.execute();
auto& resources = gatherer.output.get(); // ComputeShaderResources

// BENEFITS:
// ✅ naming.h is self-contained (no external declarations)
// ✅ SDI controls all metadata (versioning, consistency)
// ✅ Include and use - zero manual setup
// ✅ Type-safe: wrong type = compile error
// ✅ Refactoring-safe: SDI regenerates = automatic update
// ✅ Single source of truth (the shader itself)

*/
