if(NOT DEFINED LOOKDEV_CAPTURE_EXE OR NOT DEFINED LOOKDEV_CAPTURE_DIR)
    message(FATAL_ERROR "LOOKDEV_CAPTURE_EXE and LOOKDEV_CAPTURE_DIR are required")
endif()

set(_gtest_filter "--gtest_filter=LookdevCapture.RendersFourStatesAtFourAnglesDeterministically")
set(_states midday late-afternoon overcast night-service)
if(DEFINED ENV{VIXEN_LOOKDEV_CAPTURE_STATE} AND NOT "$ENV{VIXEN_LOOKDEV_CAPTURE_STATE}" STREQUAL "")
    set(_states "$ENV{VIXEN_LOOKDEV_CAPTURE_STATE}")
endif()
foreach(_state IN LISTS _states)
    set(_first_dir "${LOOKDEV_CAPTURE_DIR}/${_state}")
    set(_repeat_dir "${LOOKDEV_CAPTURE_DIR}/.repeat/${_state}")
    set(_run_logs)
    foreach(_run IN ITEMS "${_first_dir}" "${_repeat_dir}")
        set(ENV{VIXEN_LOOKDEV_CAPTURE_STATE} "${_state}")
        set(ENV{VIXEN_LOOKDEV_CAPTURE_DIR} "${_run}")
        execute_process(
            COMMAND "${LOOKDEV_CAPTURE_EXE}" "${_gtest_filter}"
            RESULT_VARIABLE _result
            OUTPUT_VARIABLE _stdout
            ERROR_VARIABLE _stderr)
        if(NOT _result STREQUAL "0")
            message(FATAL_ERROR "Look-dev ${_state} capture failed (${_result})\n${_stdout}\n${_stderr}")
        endif()
        string(REGEX MATCHALL "\\[HDRMeter\\][^\n]*" _meter_lines "${_stdout}")
        list(APPEND _run_logs "${_meter_lines}")
    endforeach()

    foreach(_angle RANGE 0 3)
        set(_filename "${_state}-angle-${_angle}.png")
        set(_first "${_first_dir}/${_filename}")
        set(_repeat "${_repeat_dir}/${_filename}")
        if(NOT EXISTS "${_first}" OR NOT EXISTS "${_repeat}")
            message(FATAL_ERROR "Missing deterministic capture: ${_first} or ${_repeat}")
        endif()
        file(SHA256 "${_first}" _first_hash)
        file(SHA256 "${_repeat}" _repeat_hash)
        if(NOT _first_hash STREQUAL _repeat_hash)
            message(FATAL_ERROR "Repeated capture pixels differ for ${_filename}\nFirst run:\n${_run_logs}")
        endif()
    endforeach()
endforeach()

list(LENGTH _states _state_count)
math(EXPR _capture_count "${_state_count} * 4")
message(STATUS "All ${_capture_count} selected look-dev captures are byte-identical across fresh per-state process runs")
