@echo off
for %%I in ("%~dp0..") do set VIXEN_ROOT=%%~fI
set VIXEN_DDGI_CORNELL_BAKED_DEMO=1
set VIXEN_SHADOW_CONFIG_ENABLED=1
set VIXEN_SHADOW_NO_MIP_ANYHIT=1
set VIXEN_SHADOW_DBG_PX=110
set VIXEN_SHADOW_DBG_PY=390
set VIXEN_HUD_CAPTURE_FRAMES=150
set VIXEN_HUD_CAPTURE_DIR=%VIXEN_ROOT%\temp_bench\sdbg_nomip
set VIXEN_EXIT_AFTER_FRAMES=160
cd /d %VIXEN_ROOT%\VIXEN
binaries\VIXEN.exe > %VIXEN_ROOT%\temp_bench\sdbg_nomip\run.log 2>&1
