// The complete freshness contract is enforced by sdf_core_kernels_check's --check invocation.
// This test makes sure the shader include under test is the generated kernel artifact and that
// both scalar and position-returning callables are present; numerical behavior is exercised by
// test_recipe_glsl_numerical_parity and test_recipe_kernel_glsl_roundtrip.

#include <gtest/gtest.h>
#include <fstream>
#include <sstream>
#include <string>

#ifndef SDF_CORE_KERNELS_GLSL_PATH
#  error "SDF_CORE_KERNELS_GLSL_PATH must be defined via CMake compile_definitions"
#endif

namespace {

std::string ReadFile(const std::string& path) {
    std::ifstream file(path);
    if (!file.good()) {
        ADD_FAILURE() << "Cannot open generated GLSL: " << path;
        return {};
    }
    std::ostringstream contents;
    contents << file.rdbuf();
    return contents.str();
}

} // namespace

TEST(SdfCoreGlslGenerated, ContainsKernelGeneratorArtifactAndCallableBodies) {
    const std::string glsl = ReadFile(SDF_CORE_KERNELS_GLSL_PATH);
    ASSERT_FALSE(glsl.empty());
    EXPECT_EQ(glsl.find("// GENERATED by Yeroket kernel-codegen (--recipe-kernels-cpp --out-glsl)"), 0u);
    EXPECT_NE(glsl.find("float SdfCore_Sphere("), std::string::npos);
    EXPECT_NE(glsl.find("vec3 SdfCore_Transform("), std::string::npos);
    EXPECT_NE(glsl.find("uint SdfCore_Hash32(uint valueBits)"), std::string::npos);
}
