// Generated by Yeroket kernel-codegen (--recipe-simd-cpp --out-tape-glsl); do not edit.
// The caller declares RecipeTapeInstruction recipeTape[] and SdfCore_* GLSL callables.
bool EvalRecipeTape(uint tapeOffset, uint tapeCount, vec3 p, out float distanceValue, out uint executedClauses) {
    float stack[64];
    int sp = 0;
    executedClauses = 0u;
    for (uint i = 0u; i < tapeCount; ++i) {
        uint instructionIndex = tapeOffset + i;
        switch (recipeTape[instructionIndex].opCode) {
            case 0u: { // Sphere
                if (sp >= 64) return false;
                stack[sp++] = SdfCore_Sphere(p, vec3(recipeTape[instructionIndex].data[0], recipeTape[instructionIndex].data[1], recipeTape[instructionIndex].data[2]), recipeTape[instructionIndex].data[3]);
                ++executedClauses;
            } break;
            case 1u: { // Box
                if (sp >= 64) return false;
                stack[sp++] = SdfCore_Box(p, vec3(recipeTape[instructionIndex].data[0], recipeTape[instructionIndex].data[1], recipeTape[instructionIndex].data[2]));
                ++executedClauses;
            } break;
            case 24u: { // Union
                if (sp < 2) return false;
                stack[sp - 2] = SdfCore_Union(stack[sp - 2], stack[sp - 1]);
                --sp;
                ++executedClauses;
            } break;
            case 26u: { // Subtract
                if (sp < 2) return false;
                stack[sp - 2] = SdfCore_Subtract(stack[sp - 2], stack[sp - 1]);
                --sp;
                ++executedClauses;
            } break;
            case 28u: { // Intersect
                if (sp < 2) return false;
                stack[sp - 2] = SdfCore_Intersect(stack[sp - 2], stack[sp - 1]);
                --sp;
                ++executedClauses;
            } break;
            default: return false;
        }
    }
    if (sp != 1) return false;
    distanceValue = stack[0];
    return true;
}
