// GENERATED by Yeroket kernel-codegen (--recipe-kernels-cpp --out-glsl) — DO NOT EDIT.

vec3 SdfCore_Bend(vec3 p, float k) {
    float c = cos(k * p.x);
    float s = sin(k * p.x);
    vec2 q = vec2(c * p.x - s * p.y, s * p.x + c * p.y);
    { precise vec3 _yeroketPreciseReturn = vec3(q.x, q.y, p.z); return _yeroketPreciseReturn; }
}

float SdfCore_Box(vec3 p, vec3 b) {
    vec3 q = abs(p) - b;
    { precise float _yeroketPreciseReturn = length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0); return _yeroketPreciseReturn; }
}

float SdfCore_BoxRounded(vec3 p, vec3 halfExtents, float roundRadius) {
    vec3 q = abs(p) - halfExtents + roundRadius;
    { precise float _yeroketPreciseReturn = length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0) - roundRadius; return _yeroketPreciseReturn; }
}

float SdfCore_CappedTorus(vec3 p, vec2 sc, float majorRadius, float minorRadius) {
    vec3 localP = p;
    localP.x = abs(localP.x);
    float k = ((sc.y * localP.x > sc.x * localP.z) ? dot(vec2(localP.x, localP.z), sc) : length(vec2(localP.x, localP.z)));
    { precise float _yeroketPreciseReturn = sqrt(dot(localP, localP) + majorRadius * majorRadius - 2.0 * majorRadius * k) - minorRadius; return _yeroketPreciseReturn; }
}

float SdfCore_Capsule(vec3 p, float height, float radius) {
    vec3 localP = p;
    localP.y -= clamp(localP.y, -height, height);
    { precise float _yeroketPreciseReturn = length(localP) - radius; return _yeroketPreciseReturn; }
}

float SdfCore_Cone(vec3 p, vec2 angle, float height) {
    vec2 q = height * vec2(angle.x / angle.y, -1.0);
    vec2 w = vec2(length(vec2(p.x, p.z)), p.y);
    vec2 a = w - q * clamp(dot(w, q) / dot(q, q), 0.0, 1.0);
    vec2 b = w - q * vec2(clamp(w.x / q.x, 0.0, 1.0), 1.0);
    float k = sign(q.y);
    float d = min(dot(a, a), dot(b, b));
    float s = max(k * (w.x * q.y - w.y * q.x), k * (w.y - q.y));
    { precise float _yeroketPreciseReturn = sqrt(d) * sign(s); return _yeroketPreciseReturn; }
}

float SdfCore_Cylinder(vec3 p, float height, float radius) {
    vec2 d = vec2(length(vec2(p.x, p.z)) - radius, abs(p.y) - height);
    { precise float _yeroketPreciseReturn = min(max(d.x, d.y), 0.0) + length(max(d, 0.0)); return _yeroketPreciseReturn; }
}

float SdfCore_Displacement(float sdf, float disp, float scale) {
    { precise float _yeroketPreciseReturn = sdf + disp * scale; return _yeroketPreciseReturn; }
}

float SdfCore_Ellipsoid(vec3 p, vec3 radii) {
    vec3 safeRadii = max(radii, 0.0001);
    float k0 = length(p / safeRadii);
    float k1 = length(p / (safeRadii * safeRadii));
    { precise float _yeroketPreciseReturn = k0 * (k0 - 1.0) / max(k1, 0.0001); return _yeroketPreciseReturn; }
}

vec3 SdfCore_Elongate(vec3 p, vec3 h) {
    { precise vec3 _yeroketPreciseReturn = p - clamp(p, -h, h); return _yeroketPreciseReturn; }
}

float SdfCore_FakeRoundCone(vec3 p, float r1, float r2, float height) {
    vec2 q = vec2(length(vec2(p.x, p.z)), p.y);
    float h = clamp(q.y / height, 0.0, 1.0);
    float r = mix(r1, r2, h);
    { precise float _yeroketPreciseReturn = length(vec2(q.x, q.y - height * h)) - r; return _yeroketPreciseReturn; }
}

vec3 SdfCore_Float3Add(vec3 a, vec3 b) {
    { precise vec3 _yeroketPreciseReturn = a + b; return _yeroketPreciseReturn; }
}

float SdfCore_Float3Dot(vec3 a, vec3 b) {
    { precise float _yeroketPreciseReturn = dot(a, b); return _yeroketPreciseReturn; }
}

vec3 SdfCore_Float3Max(vec3 a, vec3 b) {
    { precise vec3 _yeroketPreciseReturn = max(a, b); return _yeroketPreciseReturn; }
}

vec3 SdfCore_Float3Min(vec3 a, vec3 b) {
    { precise vec3 _yeroketPreciseReturn = min(a, b); return _yeroketPreciseReturn; }
}

vec3 SdfCore_Float3MulComponentWise(vec3 a, vec3 b) {
    { precise vec3 _yeroketPreciseReturn = a * b; return _yeroketPreciseReturn; }
}

vec3 SdfCore_Float3Normalize(vec3 v) {
    float lenSq = v.x * v.x + v.y * v.y + v.z * v.z;
    float invLen = (lenSq < 1e-14 ? 0.0 : 1.0 / sqrt(lenSq));
    { precise vec3 _yeroketPreciseReturn = v * invLen; return _yeroketPreciseReturn; }
}

vec3 SdfCore_Float3ScalarMul(vec3 v, float s) {
    { precise vec3 _yeroketPreciseReturn = v * s; return _yeroketPreciseReturn; }
}

vec3 SdfCore_Float3Sub(vec3 a, vec3 b) {
    { precise vec3 _yeroketPreciseReturn = a - b; return _yeroketPreciseReturn; }
}

int SdfCore_FloatToQ16(float value) {
    uint bits = floatBitsToUint(value);
    bool negative = (bits & 0x80000000u) != 0u;
    uint exponent = (bits >> 23) & 0xffu;
    uint mantissa = bits & 0x7fffffu;
    if (exponent == 0xffu)
    {
        if (mantissa != 0u)
        {
            return 0;
        }
        return (negative ? -2147483647 - 1 : 2147483647);
    }
    if (exponent == 0u)
    {
        return 0;
    }
    mantissa |= 0x800000u;
    if (exponent >= 142u)
    {
        return (negative ? -2147483647 - 1 : 2147483647);
    }
    int shift = int(exponent) - 134;
    uint magnitude = 0;
    if (shift >= 0)
    {
        magnitude = mantissa << uint(shift);
    }
    else
    {
        uint rightShift = uint((-shift));
        if (rightShift > 24u)
        {
            magnitude = 0u;
        }
        else
        {
            uint quotient = mantissa >> rightShift;
            uint remainder = mantissa & ((1u << rightShift) - 1u);
            uint halfway = 1u << (rightShift - 1u);
            if (remainder > halfway || (remainder == halfway && (quotient & 1u) != 0u))
            {
                quotient++;
            }
            magnitude = quotient;
        }
    }
    if (!negative)
    {
        return int(magnitude);
    }
    if (magnitude == 0x80000000u)
    {
        return -2147483647 - 1;
    }
    return -int(magnitude);
}

uint SdfCore_Hash32(uint valueBits) {
    uint x = valueBits;
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

uint SdfCore_Hash32Combine(uint stateBits, uint valueBits) {
    uint x = (stateBits ^ valueBits) + 0x9e3779b9u;
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}

float SdfCore_HexPrism(vec3 p, vec2 h) {
    float k0 = 0.8660254;
    float kz = 0.57735;
    vec3 q = abs(p);
    float dotVal = min(dot(vec2(-k0, 0.5), vec2(q.x, q.z)), 0.0);
    q.x -= 2.0 * dotVal * (-k0);
    q.z -= 2.0 * dotVal * 0.5;
    vec2 d = vec2(length(vec2(q.x, q.z) - vec2(clamp(q.x, -kz * h.x, kz * h.x), h.x)) * sign(q.z - h.x), q.y - h.y);
    { precise float _yeroketPreciseReturn = min(max(d.x, d.y), 0.0) + length(max(d, 0.0)); return _yeroketPreciseReturn; }
}

float SdfCore_HollowCylinder(vec3 p, float halfLen, float outerR, float wall) {
    vec2 d = vec2(length(vec2(p.x, p.z)) - outerR, abs(p.y) - halfLen);
    float cyl = min(max(d.x, d.y), 0.0) + length(max(d, 0.0));
    { precise float _yeroketPreciseReturn = abs(cyl) - wall; return _yeroketPreciseReturn; }
}

float SdfCore_Intersect(float a, float b) {
    { precise float _yeroketPreciseReturn = max(a, b); return _yeroketPreciseReturn; }
}

float SdfCore_Link(vec3 p, float halfLength, float majorRadius, float minorRadius) {
    vec3 q = vec3(p.x, max(abs(p.y) - halfLength, 0.0), p.z);
    { precise float _yeroketPreciseReturn = length(vec2(length(vec2(q.x, q.y)) - majorRadius, q.z)) - minorRadius; return _yeroketPreciseReturn; }
}

float SdfCore_MathAbs(float x) {
    { precise float _yeroketPreciseReturn = abs(x); return _yeroketPreciseReturn; }
}

float SdfCore_MathAdd(float a, float b) {
    { precise float _yeroketPreciseReturn = a + b; return _yeroketPreciseReturn; }
}

float SdfCore_MathClamp(float x, float lo, float hi) {
    { precise float _yeroketPreciseReturn = clamp(x, lo, hi); return _yeroketPreciseReturn; }
}

float SdfCore_MathCos(float x, float frequency, float phase, float amplitude) {
    { precise float _yeroketPreciseReturn = cos(x * frequency + phase) * amplitude; return _yeroketPreciseReturn; }
}

float SdfCore_MathDiv(float a, float b) {
    { precise float _yeroketPreciseReturn = (b != 0.0 ? a / b : 0.0); return _yeroketPreciseReturn; }
}

float SdfCore_MathExp(float x) {
    { precise float _yeroketPreciseReturn = exp(x); return _yeroketPreciseReturn; }
}

float SdfCore_MathFrac(float x) {
    { precise float _yeroketPreciseReturn = fract(x); return _yeroketPreciseReturn; }
}

float SdfCore_MathLerp(float a, float b, float t) {
    { precise float _yeroketPreciseReturn = mix(a, b, t); return _yeroketPreciseReturn; }
}

float SdfCore_MathLog(float x) {
    { precise float _yeroketPreciseReturn = log(max(x, 1e-30)); return _yeroketPreciseReturn; }
}

float SdfCore_MathLog2(float x) {
    { precise float _yeroketPreciseReturn = log2(max(x, 1e-30)); return _yeroketPreciseReturn; }
}

float SdfCore_MathMax(float a, float b) {
    { precise float _yeroketPreciseReturn = max(a, b); return _yeroketPreciseReturn; }
}

float SdfCore_MathMin(float a, float b) {
    { precise float _yeroketPreciseReturn = min(a, b); return _yeroketPreciseReturn; }
}

float SdfCore_MathMul(float a, float b) {
    { precise float _yeroketPreciseReturn = a * b; return _yeroketPreciseReturn; }
}

float SdfCore_MathNegate(float x) {
    { precise float _yeroketPreciseReturn = -x; return _yeroketPreciseReturn; }
}

float SdfCore_MathPow(float x, float power) {
    { precise float _yeroketPreciseReturn = pow(abs(x), power) * sign(x); return _yeroketPreciseReturn; }
}

float SdfCore_MathRemap(float x, float inMin, float inMax, float outMin, float outMax) {
    { precise float _yeroketPreciseReturn = outMin + (x - inMin) / max(inMax - inMin, 1e-8) * (outMax - outMin); return _yeroketPreciseReturn; }
}

float SdfCore_MathSaturate(float x) {
    { precise float _yeroketPreciseReturn = clamp(x, 0.0, 1.0); return _yeroketPreciseReturn; }
}

float SdfCore_MathSign(float x) {
    { precise float _yeroketPreciseReturn = sign(x); return _yeroketPreciseReturn; }
}

float SdfCore_MathSin(float x, float frequency, float phase, float amplitude) {
    { precise float _yeroketPreciseReturn = sin(x * frequency + phase) * amplitude; return _yeroketPreciseReturn; }
}

float SdfCore_MathSmoothstep(float x, float edge0, float edge1) {
    { precise float _yeroketPreciseReturn = smoothstep(edge0, edge1, x); return _yeroketPreciseReturn; }
}

float SdfCore_MathSqrt(float x) {
    { precise float _yeroketPreciseReturn = sqrt(abs(x)); return _yeroketPreciseReturn; }
}

float SdfCore_MathStep(float x, float edge) {
    { precise float _yeroketPreciseReturn = step(edge, x); return _yeroketPreciseReturn; }
}

float SdfCore_MathSub(float a, float b) {
    { precise float _yeroketPreciseReturn = a - b; return _yeroketPreciseReturn; }
}

vec3 SdfCore_MirrorX(vec3 p) {
    { precise vec3 _yeroketPreciseReturn = vec3(abs(p.x), p.y, p.z); return _yeroketPreciseReturn; }
}

vec3 SdfCore_MirrorY(vec3 p) {
    { precise vec3 _yeroketPreciseReturn = vec3(p.x, abs(p.y), p.z); return _yeroketPreciseReturn; }
}

vec3 SdfCore_MirrorZ(vec3 p) {
    { precise vec3 _yeroketPreciseReturn = vec3(p.x, p.y, abs(p.z)); return _yeroketPreciseReturn; }
}

float SdfCore_Onion(float d, float r) {
    { precise float _yeroketPreciseReturn = abs(d) - r; return _yeroketPreciseReturn; }
}

float SdfCore_Plane(vec3 p, vec3 normal, float distance) {
    { precise float _yeroketPreciseReturn = dot(p, normal) + distance; return _yeroketPreciseReturn; }
}

float SdfCore_Pyramid(vec3 p, float height) {
    float m2 = height * height + 0.25;
    vec3 q = vec3(abs(p.x), p.y, abs(p.z));
    q = ((q.z > q.x) ? vec3(q.z, q.y, q.x) : q);
    q.x -= 0.5;
    q.z -= 0.5;
    vec3 a = vec3(q.z, height * q.y - 0.5 * q.x, height * q.x + 0.5 * q.y);
    float s = max(-a.x, 0.0);
    float t = clamp((a.y - 0.5 * q.z) / (m2 + 0.25), 0.0, 1.0);
    float da = m2 * (a.x + s) * (a.x + s) + a.y * a.y;
    float db = m2 * (a.x + 0.5 * t) * (a.x + 0.5 * t) + (a.y - m2 * t) * (a.y - m2 * t);
    float d2 = ((min(a.y, -a.x * m2 - a.y * 0.5) > 0.0) ? 0.0 : min(da, db));
    { precise float _yeroketPreciseReturn = sqrt((d2 + a.z * a.z) / m2) * sign(max(a.z, -q.y)); return _yeroketPreciseReturn; }
}

int SdfCore_Q16Add(int a, int b) {
    if (b > 0 && a > 2147483647 - b)
    {
        return 2147483647;
    }
    if (b < 0 && a < -2147483647 - 1 - b)
    {
        return -2147483647 - 1;
    }
    return a + b;
}

uint SdfCore_Q16Equal(int a, int b) {
    return (a == b ? 1u : 0u);
}

uint SdfCore_Q16Greater(int a, int b) {
    return (a > b ? 1u : 0u);
}

uint SdfCore_Q16GreaterEqual(int a, int b) {
    return (a >= b ? 1u : 0u);
}

uint SdfCore_Q16Less(int a, int b) {
    return (a < b ? 1u : 0u);
}

uint SdfCore_Q16LessEqual(int a, int b) {
    return (a <= b ? 1u : 0u);
}

int SdfCore_Q16Max(int a, int b) {
    return max(a, b);
}

int SdfCore_Q16Min(int a, int b) {
    return min(a, b);
}

int SdfCore_Q16Mul(int a, int b) {
    bool negative = (a < 0) != (b < 0);
    uint aMagnitude = (a < 0 ? uint((-(a + 1))) + 1u : uint(a));
    uint bMagnitude = (b < 0 ? uint((-(b + 1))) + 1u : uint(b));
    uint aLow = aMagnitude & 0xffffu;
    uint aHigh = aMagnitude >> 16;
    uint bLow = bMagnitude & 0xffffu;
    uint bHigh = bMagnitude >> 16;
    uint lowProduct = aLow * bLow;
    uint middle = aHigh * bLow + (lowProduct >> 16);
    uint middleLow = middle & 0xffffu;
    uint middleHigh = middle >> 16;
    middle = aLow * bHigh + middleLow;
    uint productLow = (middle << 16) | (lowProduct & 0xffffu);
    uint productHigh = aHigh * bHigh + middleHigh + (middle >> 16);
    uint remainder = productLow & 0xffffu;
    uint roundedLow = (productHigh << 16) | (productLow >> 16);
    uint roundedHigh = productHigh >> 16;
    if (remainder > 0x8000u || (remainder == 0x8000u && (roundedLow & 1u) != 0u))
    {
        roundedLow++;
        if (roundedLow == 0u)
        {
            roundedHigh++;
        }
    }
    uint limit = (negative ? 0x80000000u : 0x7fffffffu);
    if (roundedHigh != 0u || roundedLow > limit)
    {
        return (negative ? -2147483647 - 1 : 2147483647);
    }
    if (!negative)
    {
        return int(roundedLow);
    }
    if (roundedLow == 0x80000000u)
    {
        return -2147483647 - 1;
    }
    return -int(roundedLow);
}

uint SdfCore_Q16NotEqual(int a, int b) {
    return (a != b ? 1u : 0u);
}

int SdfCore_Q16Sub(int a, int b) {
    if (b < 0 && a > 2147483647 + b)
    {
        return 2147483647;
    }
    if (b > 0 && a < -2147483647 - 1 + b)
    {
        return -2147483647 - 1;
    }
    return a - b;
}

float SdfCore_Q16ToFloat(int value) {
    { precise float _yeroketPreciseReturn = float(value) * (1.0 / 65536.0); return _yeroketPreciseReturn; }
}

uint SdfCore_Q16ToU32(int value) {
    if (value < 0)
    {
        return 0u;
    }
    uint whole = uint(value) >> 16;
    uint remainder = uint(value) & 0xffffu;
    if (remainder > 0x8000u || (remainder == 0x8000u && (whole & 1u) != 0u))
    {
        whole++;
    }
    if (whole > 0xffffffffu)
    {
        return 0xffffffffu;
    }
    return whole;
}

vec3 SdfCore_RepeatInfinite(vec3 p, vec3 spacing) {
    { precise vec3 _yeroketPreciseReturn = mod(abs(p) + spacing * 0.5, spacing) - spacing * 0.5; return _yeroketPreciseReturn; }
}

vec3 SdfCore_RepeatLimited(vec3 p, float spacing, vec3 limit) {
    { precise vec3 _yeroketPreciseReturn = p - spacing * clamp(round(p / spacing), -limit, limit); return _yeroketPreciseReturn; }
}

vec3 SdfCore_Revolution(vec3 p, vec3 center, float offset) {
    vec3 pp = p - center;
    vec2 q = vec2(length(vec2(pp.x, pp.z)) - offset, pp.y);
    { precise vec3 _yeroketPreciseReturn = vec3(q.x, q.y, 0) + center; return _yeroketPreciseReturn; }
}

float SdfCore_Round(float d, float r) {
    { precise float _yeroketPreciseReturn = d - r; return _yeroketPreciseReturn; }
}

float SdfCore_RoundCone(vec3 p, float r1, float r2, float height) {
    vec2 q = vec2(length(vec2(p.x, p.z)), p.y);
    float b = (r1 - r2) / height;
    float a = sqrt(1.0 - b * b);
    float k = dot(q, vec2(-b, a));
    float regionA = length(q) - r1;
    float regionB = length(q - vec2(0.0, height)) - r2;
    float regionC = dot(q, vec2(a, b)) - r1;
    float d = ((k < 0.0) ? regionA : regionC);
    d = ((k > a * height) ? regionB : d);
    { precise float _yeroketPreciseReturn = d; return _yeroketPreciseReturn; }
}

float SdfCore_Segment(vec3 p, vec3 a, vec3 b, float radius) {
    vec3 pa = p - a;
    vec3 ba = b - a;
    float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    { precise float _yeroketPreciseReturn = length(pa - ba * h) - radius; return _yeroketPreciseReturn; }
}

float SdfCore_Select(float cond, float a, float b, float thr) {
    { precise float _yeroketPreciseReturn = (cond > thr ? a : b); return _yeroketPreciseReturn; }
}

float SdfCore_SmoothIntersect(float a, float b, float k) {
    float h = clamp(0.5 - 0.5 * (b - a) / k, 0.0, 1.0);
    { precise float _yeroketPreciseReturn = mix(b, a, h) + k * h * (1.0 - h); return _yeroketPreciseReturn; }
}

float SdfCore_SmoothIntersectCubic(float a, float b, float k) {
    float h = max(k - abs(a - b), 0.0) / k;
    { precise float _yeroketPreciseReturn = max(a, b) + h * h * h * k * (1.0 / 6.0); return _yeroketPreciseReturn; }
}

float SdfCore_SmoothMax(float a, float b, float k) {
    float h = max(k - abs(a - b), 0.0) / k;
    { precise float _yeroketPreciseReturn = max(a, b) + h * h * h * k * (1.0 / 6.0); return _yeroketPreciseReturn; }
}

float SdfCore_SmoothSubtract(float a, float b, float k) {
    float h = clamp(0.5 - 0.5 * (b + a) / k, 0.0, 1.0);
    { precise float _yeroketPreciseReturn = mix(a, -b, h) + k * h * (1.0 - h); return _yeroketPreciseReturn; }
}

float SdfCore_SmoothSubtractCubic(float a, float b, float k) {
    float h = max(k - abs(-b - a), 0.0) / k;
    { precise float _yeroketPreciseReturn = max(a, -b) + h * h * h * k * (1.0 / 6.0); return _yeroketPreciseReturn; }
}

float SdfCore_SmoothUnion(float a, float b, float k) {
    float h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
    { precise float _yeroketPreciseReturn = mix(b, a, h) - k * h * (1.0 - h); return _yeroketPreciseReturn; }
}

float SdfCore_SmoothUnionCubic(float a, float b, float k) {
    float h = max(k - abs(a - b), 0.0) / k;
    { precise float _yeroketPreciseReturn = min(a, b) - h * h * h * k * (1.0 / 6.0); return _yeroketPreciseReturn; }
}

float SdfCore_Sphere(vec3 p, vec3 center, float radius) {
    { precise float _yeroketPreciseReturn = length(p - center) - radius; return _yeroketPreciseReturn; }
}

float SdfCore_Subtract(float a, float b) {
    { precise float _yeroketPreciseReturn = max(a, -b); return _yeroketPreciseReturn; }
}

float SdfCore_TaperedCylinder(vec3 p, float height, float r1, float r2) {
    vec2 q = vec2(length(vec2(p.x, p.z)), p.y);
    vec2 k1 = vec2(r2, height);
    vec2 k2 = vec2(r2 - r1, 2.0 * height);
    vec2 ca = vec2(q.x - min(q.x, ((q.y < 0.0) ? r1 : r2)), abs(q.y) - height);
    vec2 cb = q - k1 + k2 * clamp(dot(k1 - q, k2) / dot(k2, k2), 0.0, 1.0);
    float s = ((cb.x < 0.0 && ca.y < 0.0) ? -1.0 : 1.0);
    { precise float _yeroketPreciseReturn = s * sqrt(min(dot(ca, ca), dot(cb, cb))); return _yeroketPreciseReturn; }
}

float SdfCore_Torus(vec3 p, float majorRadius, float minorRadius) {
    vec2 q = vec2(length(vec2(p.x, p.z)) - majorRadius, p.y);
    { precise float _yeroketPreciseReturn = length(q) - minorRadius; return _yeroketPreciseReturn; }
}

vec3 SdfCore_Transform(vec3 p, vec3 translation, vec4 invRotXYZW, vec3 invScale) {
    vec3 v = p - translation;
    vec3 qv = vec3(invRotXYZW.x, invRotXYZW.y, invRotXYZW.z);
    float qw = invRotXYZW.w;
    vec3 t = 2.0 * cross(qv, v);
    vec3 rotated = v + qw * t + cross(qv, t);
    { precise vec3 _yeroketPreciseReturn = rotated * invScale; return _yeroketPreciseReturn; }
}

float SdfCore_TriangularPrism(vec3 p, vec2 h) {
    vec3 q = abs(p);
    { precise float _yeroketPreciseReturn = max(q.z - h.y, max(q.x * 0.866025 + p.y * 0.5, -p.y) - h.x * 0.5); return _yeroketPreciseReturn; }
}

vec3 SdfCore_Twist(vec3 p, float k) {
    float c = cos(k * p.y);
    float s = sin(k * p.y);
    vec2 q = vec2(c * p.x - s * p.z, s * p.x + c * p.z);
    { precise vec3 _yeroketPreciseReturn = vec3(q.x, p.y, q.y); return _yeroketPreciseReturn; }
}

uint SdfCore_U32Add(uint a, uint b) {
    return a + b;
}

uint SdfCore_U32Equal(uint a, uint b) {
    return (a == b ? 1u : 0u);
}

uint SdfCore_U32Greater(uint a, uint b) {
    return (a > b ? 1u : 0u);
}

uint SdfCore_U32GreaterEqual(uint a, uint b) {
    return (a >= b ? 1u : 0u);
}

uint SdfCore_U32Less(uint a, uint b) {
    return (a < b ? 1u : 0u);
}

uint SdfCore_U32LessEqual(uint a, uint b) {
    return (a <= b ? 1u : 0u);
}

uint SdfCore_U32Max(uint a, uint b) {
    return max(a, b);
}

uint SdfCore_U32Min(uint a, uint b) {
    return min(a, b);
}

uint SdfCore_U32Mul(uint a, uint b) {
    return a * b;
}

uint SdfCore_U32NotEqual(uint a, uint b) {
    return (a != b ? 1u : 0u);
}

uint SdfCore_U32Sub(uint a, uint b) {
    return a - b;
}

float SdfCore_U32ToFloat(uint value) {
    { precise float _yeroketPreciseReturn = float(value); return _yeroketPreciseReturn; }
}

int SdfCore_U32ToQ16(uint value) {
    if (value > 32767u)
    {
        return 2147483647;
    }
    return int((value << 16));
}

float SdfCore_Union(float a, float b) {
    { precise float _yeroketPreciseReturn = min(a, b); return _yeroketPreciseReturn; }
}

float SdfCore_Xor(float a, float b) {
    { precise float _yeroketPreciseReturn = max(min(a, b), -max(a, b)); return _yeroketPreciseReturn; }
}
